### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by GoliathLabs** [psi-4ward/hello-world-container#7]
One thing I noticed after making the CSS changes is that the headers are no longer enclosed in the blue container. There is probably very little to do to get everything working again

![image](https://user-images.githubusercontent.com/8057646/137361432-6e047d9d-9637-423f-8f60-2610e9669b2e.png)

**Comment by psi-4ward** [comment]
No worries :) think there is some panel/card stuff changed in bootstrap 5
Didnt use it for a loooong time ;)
